language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps

elixir:
  - 1.6
  - 1.7
  - 1.8

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test

otp_release:
  - 19.3
  - 20.3
  - 21.0

services:
  - redis-server
