language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps

elixir:
  - 1.6
  - 1.7
  - 1.8

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
  - mix coveralls.travis

otp_release:
  - 20.3
  - 21.0

services:
  - redis-server

deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
